package formularios;

import dao.DPersona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Sexo;

/**
 *
 * @author Gabriel Chang
 */
public class FrmPersona extends javax.swing.JFrame {
    DPersona dp = new DPersona();
    private int pos = 0;
    /**
     * Creates new form FrmPersona
     */
    public FrmPersona() {
        initComponents();
        jBtnLimpiar.setToolTipText("Limpiar");
        jBtnAgregar.setToolTipText("Agregar");
        jCmbSexo.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblId = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jCmbSexo = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnLimpiar = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnPrimero = new javax.swing.JButton();
        jBtnAnterior = new javax.swing.JButton();
        jBtnSiguiente = new javax.swing.JButton();
        jBtnUltimo = new javax.swing.JButton();
        jLblEmail1 = new javax.swing.JLabel();
        jTfId = new javax.swing.JTextField();
        jTfNombre = new javax.swing.JTextField();
        jTfApellidos = new javax.swing.JTextField();
        jTfEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRegistros = new javax.swing.JTable();
        jLblRegTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de Personas");

        jLblId.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLblId.setText("ID:");

        jLblNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLblNombre.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Apellidos:");

        jLblEmail.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLblEmail.setText("Email:");

        jCmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jToolBar1.setRollover(true);

        jBtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complemento/img/nuevo-producto.png"))); // NOI18N
        jBtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLimpiar.setFocusable(false);
        jBtnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnLimpiar);

        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complemento/img/disquete.png"))); // NOI18N
        jBtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAgregar.setFocusable(false);
        jBtnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAgregar);

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complemento/img/editar.png"))); // NOI18N
        jBtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnEditar.setEnabled(false);
        jBtnEditar.setFocusable(false);
        jBtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnEditar);

        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complemento/img/boton-eliminar.png"))); // NOI18N
        jBtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.setFocusable(false);
        jBtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnEliminar);
        jToolBar1.add(jSeparator1);

        jBtnPrimero.setText("|<");
        jBtnPrimero.setFocusable(false);
        jBtnPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrimeroActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnPrimero);

        jBtnAnterior.setText("<<");
        jBtnAnterior.setFocusable(false);
        jBtnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnteriorActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAnterior);

        jBtnSiguiente.setText(">>");
        jBtnSiguiente.setFocusable(false);
        jBtnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSiguienteActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnSiguiente);

        jBtnUltimo.setText(">|");
        jBtnUltimo.setFocusable(false);
        jBtnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUltimoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnUltimo);

        jLblEmail1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLblEmail1.setText("Sexo:");

        jTblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblRegistros);

        jLblRegTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLblRegTitle.setText("Tabla con Registros Ingresados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLblEmail)
                                    .addComponent(jLblEmail1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfApellidos)
                                    .addComponent(jTfEmail)
                                    .addComponent(jCmbSexo, 0, 163, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblId)
                                    .addComponent(jLblNombre))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jTfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jTfId, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLblRegTitle)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblRegTitle)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblId)
                            .addComponent(jTfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblNombre)
                            .addComponent(jTfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblEmail)
                            .addComponent(jTfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblEmail1)
                            .addComponent(jCmbSexo))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        
        //validar campo vacio ID
        if(jTfId.getText() == "" || jTfId.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Necesita  Agregar el ID", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //validar campo vacio Nombre
        if(jTfNombre.getText() == "" || jTfNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Necesita  Agregar el Nombre", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //validar campo vacio Apellidos
        if(jTfApellidos.getText() == "" || jTfApellidos.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Necesita  Agregar los Apellidos", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //validar campo vacio Email
        if(jTfEmail.getText() == "" || jTfEmail.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Necesita  Agregar el Email", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //validar campo Sexo
        if(jCmbSexo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Necesita Agregar un Sexo",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int id = Integer.parseInt(jTfId.getText());
        //HOla
        String nombre = jTfNombre.getText();
        
        String apellidos = jTfApellidos.getText();
        
        String email = jTfEmail.getText();
        
        Sexo s;
        
        if (jCmbSexo.getSelectedIndex() == 0) 
            s = Sexo.HOMBRE;
        else 
            s = Sexo.MUJER;
        
        int b = dp.agregarPersona(id, nombre, apellidos, email, s);
        
        if(b == 1) {
            JOptionPane.showMessageDialog(this, "Registro Agregado...", 
                    "Guardar", JOptionPane.INFORMATION_MESSAGE);
            llenarTabla();
            Limpiar();
        }
        else {
            JOptionPane.showMessageDialog(this, "Error al guardar...", 
                    "Guardar", JOptionPane.ERROR_MESSAGE);
        }
        llenarTabla();
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrimeroActionPerformed
        // TODO add your handling code here:
        if (!dp.getListPersona().isEmpty()) {
            try {
                pos = 0;
                int id = dp.getListPersona().get(pos).getId();
                String nom = dp.getListPersona().get(pos).getNombre();
                String ape = dp.getListPersona().get(pos).getApellido();
                String ema = dp.getListPersona().get(pos).getEmail();
                Sexo sex = dp.getListPersona().get(pos).getSexo();
                
                jTfId.setText(""+id);
                jTfNombre.setText(nom);
                jTfApellidos.setText(ape);
                jTfEmail.setText(ema);
                
                if (sex == Sexo.HOMBRE) jCmbSexo.setSelectedIndex(0);
                else jCmbSexo.setSelectedIndex(1);
                
                jBtnAgregar.setEnabled(false);
                jBtnEditar.setEnabled(true);
                jBtnEliminar.setEnabled(true);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay registro...", "Registros",
                    JOptionPane.ERROR_MESSAGE);
        }
            
        
        
    }//GEN-LAST:event_jBtnPrimeroActionPerformed

    private void jBtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUltimoActionPerformed
        // TODO add your handling code here:
        if (!dp.getListPersona().isEmpty()){
            try {
                pos = dp.getListPersona().size() - 1;
                int id = dp.getListPersona().get(pos).getId();
                String nom = dp.getListPersona().get(pos).getNombre();
                String ape = dp.getListPersona().get(pos).getApellido();
                String ema = dp.getListPersona().get(pos).getEmail();
                Sexo sex = dp.getListPersona().get(pos).getSexo();
                
                jTfId.setText(""+id);
                jTfNombre.setText(nom);
                jTfApellidos.setText(ape);
                jTfEmail.setText(ema);
                
                if (sex == Sexo.HOMBRE) jCmbSexo.setSelectedIndex(0);
                else jCmbSexo.setSelectedIndex(1);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay registro...", "Registros",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnUltimoActionPerformed

    private void jBtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnteriorActionPerformed
        // TODO add your handling code here:
        if (!dp.getListPersona().isEmpty()){
            try {
                pos--;
                if (pos < 0) pos = dp.getListPersona().size() - 1;
                int id = dp.getListPersona().get(pos).getId();
                String nom = dp.getListPersona().get(pos).getNombre();
                String ape = dp.getListPersona().get(pos).getApellido();
                String ema = dp.getListPersona().get(pos).getEmail();
                Sexo sex = dp.getListPersona().get(pos).getSexo();
                
                jTfId.setText(""+id);
                jTfNombre.setText(nom);
                jTfApellidos.setText(ape);
                jTfEmail.setText(ema);
                
                if (sex == Sexo.HOMBRE) jCmbSexo.setSelectedIndex(0);
                else jCmbSexo.setSelectedIndex(1);
                
                jBtnAgregar.setEnabled(false);
                jBtnEditar.setEnabled(true);
                jBtnEliminar.setEnabled(true);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay registro...", "Registros",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAnteriorActionPerformed

    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
        // TODO add your handling code here:
        if (!dp.getListPersona().isEmpty()){
            try {
                pos++;
                if (pos == dp.getListPersona().size()) pos = 0;
                int id = dp.getListPersona().get(pos).getId();
                String nom = dp.getListPersona().get(pos).getNombre();
                String ape = dp.getListPersona().get(pos).getApellido();
                String ema = dp.getListPersona().get(pos).getEmail();
                Sexo sex = dp.getListPersona().get(pos).getSexo();
                
                jTfId.setText(""+id);
                jTfNombre.setText(nom);
                jTfApellidos.setText(ape);
                jTfEmail.setText(ema);
                
                if (sex == Sexo.HOMBRE) jCmbSexo.setSelectedIndex(0);
                else jCmbSexo.setSelectedIndex(1);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay registro...", "Registros",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnSiguienteActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        dp.getListPersona().get(pos).setId(Integer.parseInt(jTfId.getText()));
        dp.getListPersona().get(pos).setNombre(jTfNombre.getText());
        dp.getListPersona().get(pos).setApellido(jTfApellidos.getText());
        dp.getListPersona().get(pos).setEmail(jTfEmail.getText());
        if(jCmbSexo.getSelectedIndex() == 0)
            dp.getListPersona().get(pos).setSexo(Sexo.HOMBRE);
        else
            dp.getListPersona().get(pos).setSexo(Sexo.MUJER);
        
        JOptionPane.showMessageDialog(this, "Cambios realizados...", "Editar", 
                JOptionPane.INFORMATION_MESSAGE);

        llenarTabla();
        Limpiar();
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        int op;
        op = JOptionPane.showConfirmDialog(this, "Desea eliminar?", 
                "Eliminar", JOptionPane.YES_NO_OPTION);
        
        if(op == 0) {
            dp.getListPersona().remove(pos);
            JOptionPane.showMessageDialog(this, "Ok");
            
            llenarTabla();
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Operacion cancelada.");
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void llenarTabla() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl = dp.getListPer();
        jTblRegistros.setModel(tbl);
    }
    
    private void Limpiar() {
        jTfId.setText("");
        jTfNombre.setText("");
        jTfApellidos.setText("");
        jTfEmail.setText("");
        jCmbSexo.setSelectedIndex(-1);
        
        jBtnAgregar.setEnabled(false);
        jBtnEditar.setEnabled(true);
        jBtnEliminar.setEnabled(true);
        
        jTfId.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnAnterior;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnPrimero;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JButton jBtnUltimo;
    private javax.swing.JComboBox<String> jCmbSexo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEmail1;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblRegTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTblRegistros;
    private javax.swing.JTextField jTfApellidos;
    private javax.swing.JTextField jTfEmail;
    private javax.swing.JTextField jTfId;
    private javax.swing.JTextField jTfNombre;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
